- hosts: child
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Create web root directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Copy index.html
      copy:
        src: /home/ubuntu/website/index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Copy style.css
      copy:
        src: /home/ubuntu/website/style.css
        dest: /var/www/html/style.css
        mode: '0644'

    - name: Copy script.js
      copy:
        src: /home/ubuntu/website/script.js
        dest: /var/www/html/script.js
        mode: '0644'

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
